# If you have any process.env variables, this is where they should be specified.
service: datasheet-server-1
runtime: nodejs12
instance_class: F1
automatic_scaling:
  max_instances: 1

env_variables:
  NODE_ENV: "development"
  SERVICE_ACCOUNT_EMAIL: "forensic-265906@appspot.gserviceaccount.com"
  SERVICE_ACCOUNT_PRIVATE_KEY: ${_SERVICE_ACCOUNT_PRIVATE_KEY}
