steps:
- name: node
  entrypoint: npm
  args: ['install']
- name: node
  entrypoint: npm
  args: ['test']
- name: node
  entrypoint: npm
  env:
  - 'SERVICE_ACCOUNT_EMAIL=${_SERVICE_ACCOUNT_EMAIL}'
  - 'SERVICE_ACCOUNT_PRIVATE_KEY=${_SERVICE_ACCOUNT_PRIVATE_KEY}'
  args: ['run', 'build']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
  env:
  - 'SERVICE_ACCOUNT_EMAIL=${_SERVICE_ACCOUNT_EMAIL}'
  - 'SERVICE_ACCOUNT_PRIVATE_KEY=${_SERVICE_ACCOUNT_PRIVATE_KEY}'
  timeout: '1600s'

tags: ['forensic-architecture', 'datasheet-server', 'project-name']
